const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const DECREASE_CART = 'DECREASE_CART';
const INCREASE_CART = 'INCREASE_CART';
const REMOVE_FROM_CART_AND_ADD_TO_FAVORITE = 'REMOVE_FROM_CART_AND_ADD_TO_FAVORITE';
const SET_FAVORITE = 'SET_FAVORITE';
const PRODUCT_LENGTH = 'PRODUCT_LENGTH';
const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_FAVORITE_MENU = 'SET_FAVORITE_MENU';
const SET_SETTING_MENU = 'SET_SETTING_MENU';

export const actionTypes = {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  DECREASE_CART,
  INCREASE_CART,
  REMOVE_FROM_CART_AND_ADD_TO_FAVORITE,
  SET_FAVORITE,
  PRODUCT_LENGTH,
  SET_SEARCH_VALUE,
  SET_FAVORITE_MENU,
  SET_SETTING_MENU,
};
