export { ReactComponent as LogoSvg } from '../../assets/svg/logo.svg';
export { ReactComponent as CartSvg } from '../../assets/svg/cart.svg';
export { ReactComponent as FavoriteSvg } from '../../assets/svg/favorite.svg';
export { ReactComponent as ArrowSvg } from '../../assets/svg/arrow.svg';
export { ReactComponent as LikeSvg } from '../../assets/svg/like.svg';
export { ReactComponent as CloseSvg } from '../../assets/svg/close.svg';
export { ReactComponent as TrashSvg } from '../../assets/svg/trash.svg';
export { ReactComponent as PlusSvg } from '../../assets/svg/plus.svg';
export { ReactComponent as MinusSvg } from '../../assets/svg/minus.svg';
